<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button Close Chat</name>
   <tag></tag>
   <elementGuidId>d830d7ba-a81b-472e-924f-335facf9b370</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'button' and @title = 'Close' and @class = 'dolphin-message-logout']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;dolphin-chat-close&quot;]/button[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70c3dbb4-5625-47a9-8bff-6a164935401d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5966a19f-06bd-41c7-aaae-61f097d50871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>7f0d1fe8-6a70-4d71-88e7-b2f4149209e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dolphin-message-logout</value>
      <webElementGuid>47fe0a55-0891-4661-b1db-b8bbe64e9ade</webElementGuid>
   </webElementProperties>
</WebElementEntity>
