<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_Telephone</name>
   <tag></tag>
   <elementGuidId>0a092b5e-d0c9-4002-9fbb-d096b4acfdf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'dolphin-telephone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>354e82d1-ff0d-4346-ad22-2da454af846c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dolphin-telephone</value>
      <webElementGuid>c8cdcb43-a07a-4c47-86ca-fcbc0074f90d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
