<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_Nama</name>
   <tag></tag>
   <elementGuidId>b737647e-5f95-4b16-9648-4c7ee2cd843c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'dolphin-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa3866c5-e9ec-4b9b-9e0c-9b9c94ad820c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dolphin-name</value>
      <webElementGuid>f10edb61-3c2f-4ae0-a607-3eac1bf41b3a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
