<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WarningField_Email</name>
   <tag></tag>
   <elementGuidId>83e4fdd3-a03e-4f2e-a300-e2dd50e53e1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@id = 'dolphin-warning-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7b935930-ddc6-4a07-b3da-598eae0ee997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dolphin-warning-email</value>
      <webElementGuid>c39a81ea-f989-4e2e-8bac-738ed782a947</webElementGuid>
   </webElementProperties>
</WebElementEntity>
