<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WarningField_Telephone</name>
   <tag></tag>
   <elementGuidId>0d91404f-3828-442d-8865-e50e68147e84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@id = 'dolphin-warning-phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>45e60fd9-2ca0-42c4-b079-8dd4e8e98264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dolphin-warning-phone</value>
      <webElementGuid>15de86f7-e6e8-417b-914e-323e44a853e4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
