<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WarningField_Nama</name>
   <tag></tag>
   <elementGuidId>c1141fd1-eb57-4133-b899-f90b42e09c41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@id = 'dolphin-warning-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c3523eeb-2e63-4543-a9ea-43d8f6807905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dolphin-warning-name</value>
      <webElementGuid>23dd637e-6464-4d85-9cca-3c40572b78c5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
